portfolio_task:
  outputs:
    local_postgres:
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5434
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: local_postgres
